
    create table categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id int4 generated by default as identity,
        name varchar(255),
        id_estado int4,
        primary key (id)
    );

    create table cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        id_cidade int4,
        id_cliente int4,
        primary key (id)
    );

    create table estado (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        id_pedido int4 not null,
        id_produto int4 not null,
        primary key (id_pedido, id_produto)
    );

    create table pagamento (
       id_pedido int4 not null,
        estado int4,
        primary key (id_pedido)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pedido (
       id int4 generated by default as identity,
        instance timestamp,
        id_cliente int4,
        id_endereco_de_entrega int4,
        primary key (id)
    );

    create table produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table produto_categoria (
       id_produto int4 not null,
        id_categoria int4 not null
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists cliente 
       add constraint UK_cmxo70m08n43599l3h0h07cc6 unique (email);

    alter table if exists cidade 
       add constraint FKjn311p28f0okajvcboowr5kpo 
       foreign key (id_estado) 
       references estado;

    alter table if exists endereco 
       add constraint FKhu4avfrkfp65jedddkxe70r9a 
       foreign key (id_cidade) 
       references cidade;

    alter table if exists endereco 
       add constraint FKe4y3uftwnlua4wuwisldhnjl4 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists item_pedido 
       add constraint FKnjghutiejefh2auj9bnpf9sp7 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists item_pedido 
       add constraint FKnqncqw8pnv54kv0dct6mo2iei 
       foreign key (id_produto) 
       references produto;

    alter table if exists pagamento 
       add constraint FKr0y4u4wge04ftnh22vhmid0ee 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKd3jpogyjw7jnfci85k129798t 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FKs0xinbw8jhmda3322040yl3g4 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pedido 
       add constraint FK9y4jnyp1hxqa386cnly0ay9uw 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists pedido 
       add constraint FKpsn6c2lkfsa1seug24pmgystp 
       foreign key (id_endereco_de_entrega) 
       references endereco;

    alter table if exists produto_categoria 
       add constraint FK7w4lfcoga9id6t8qnksuntr8x 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists produto_categoria 
       add constraint FKemku9l38evdgoufg806728kcf 
       foreign key (id_produto) 
       references produto;

    alter table if exists telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id int4 generated by default as identity,
        name varchar(255),
        id_estado int4,
        primary key (id)
    );

    create table cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        id_cidade int4,
        id_cliente int4,
        primary key (id)
    );

    create table estado (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        id_pedido int4 not null,
        id_produto int4 not null,
        primary key (id_pedido, id_produto)
    );

    create table pagamento (
       id_pedido int4 not null,
        estado int4,
        primary key (id_pedido)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pedido (
       id int4 generated by default as identity,
        instance timestamp,
        id_cliente int4,
        id_endereco_de_entrega int4,
        primary key (id)
    );

    create table produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table produto_categoria (
       id_produto int4 not null,
        id_categoria int4 not null
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists cliente 
       add constraint UK_cmxo70m08n43599l3h0h07cc6 unique (email);

    alter table if exists cidade 
       add constraint FKjn311p28f0okajvcboowr5kpo 
       foreign key (id_estado) 
       references estado;

    alter table if exists endereco 
       add constraint FKhu4avfrkfp65jedddkxe70r9a 
       foreign key (id_cidade) 
       references cidade;

    alter table if exists endereco 
       add constraint FKe4y3uftwnlua4wuwisldhnjl4 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists item_pedido 
       add constraint FKnjghutiejefh2auj9bnpf9sp7 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists item_pedido 
       add constraint FKnqncqw8pnv54kv0dct6mo2iei 
       foreign key (id_produto) 
       references produto;

    alter table if exists pagamento 
       add constraint FKr0y4u4wge04ftnh22vhmid0ee 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKd3jpogyjw7jnfci85k129798t 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FKs0xinbw8jhmda3322040yl3g4 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pedido 
       add constraint FK9y4jnyp1hxqa386cnly0ay9uw 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists pedido 
       add constraint FKpsn6c2lkfsa1seug24pmgystp 
       foreign key (id_endereco_de_entrega) 
       references endereco;

    alter table if exists produto_categoria 
       add constraint FK7w4lfcoga9id6t8qnksuntr8x 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists produto_categoria 
       add constraint FKemku9l38evdgoufg806728kcf 
       foreign key (id_produto) 
       references produto;

    alter table if exists telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id int4 generated by default as identity,
        name varchar(255),
        id_estado int4,
        primary key (id)
    );

    create table cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        id_cidade int4,
        id_cliente int4,
        primary key (id)
    );

    create table estado (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        id_pedido int4 not null,
        id_produto int4 not null,
        primary key (id_pedido, id_produto)
    );

    create table pagamento (
       id_pedido int4 not null,
        estado int4,
        primary key (id_pedido)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        id_pedido int4 not null,
        primary key (id_pedido)
    );

    create table pedido (
       id int4 generated by default as identity,
        instance timestamp,
        id_cliente int4,
        id_endereco_de_entrega int4,
        primary key (id)
    );

    create table produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table produto_categoria (
       id_produto int4 not null,
        id_categoria int4 not null
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists cliente 
       add constraint UK_cmxo70m08n43599l3h0h07cc6 unique (email);

    alter table if exists cidade 
       add constraint FKjn311p28f0okajvcboowr5kpo 
       foreign key (id_estado) 
       references estado;

    alter table if exists endereco 
       add constraint FKhu4avfrkfp65jedddkxe70r9a 
       foreign key (id_cidade) 
       references cidade;

    alter table if exists endereco 
       add constraint FKe4y3uftwnlua4wuwisldhnjl4 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists item_pedido 
       add constraint FKnjghutiejefh2auj9bnpf9sp7 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists item_pedido 
       add constraint FKnqncqw8pnv54kv0dct6mo2iei 
       foreign key (id_produto) 
       references produto;

    alter table if exists pagamento 
       add constraint FKr0y4u4wge04ftnh22vhmid0ee 
       foreign key (id_pedido) 
       references pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKd3jpogyjw7jnfci85k129798t 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FKs0xinbw8jhmda3322040yl3g4 
       foreign key (id_pedido) 
       references pagamento;

    alter table if exists pedido 
       add constraint FK9y4jnyp1hxqa386cnly0ay9uw 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists pedido 
       add constraint FKpsn6c2lkfsa1seug24pmgystp 
       foreign key (id_endereco_de_entrega) 
       references endereco;

    alter table if exists produto_categoria 
       add constraint FK7w4lfcoga9id6t8qnksuntr8x 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists produto_categoria 
       add constraint FKemku9l38evdgoufg806728kcf 
       foreign key (id_produto) 
       references produto;

    alter table if exists telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;
